from mage_ai.errors.base import MageBaseException


class ValidationError(MageBaseException):
    pass
